---
title: "CRG - Diciembre 2025"
author: "R. Hidalgo"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

# Packages

```{r}
library(tidyverse)
library(readxl)
library(googlesheets4)
```

# Data

Cargar directamente desde google drive.

```{r}
# autenticarse
gs4_auth()
```

```{r}
guiri <- read_sheet("https://docs.google.com/spreadsheets/d/1e3I_ZNGK9T5HO8O65XIDaqVuQW3CVepsr2Xes4vQomQ/edit?gid=0#gid=0",
                    col_types = "ccic?_c??ii?nnnnnncc")

pelonas <- read_sheet("https://docs.google.com/spreadsheets/d/1Wfrk7pYV3NL6e0GfFpUyrNkbnNzo4K-c8v4wh2frpxg/edit?gid=0#gid=0",
                      col_types = "ccic?c??ii?nnnnnncc")

blanca <- read_sheet("https://docs.google.com/spreadsheets/d/1eHiacpuFKptxus88seAveMikQxcBYYygM6a-QOQ-bpY/edit?gid=0#gid=0",
                     col_types = "ccic?c??ii?nnnnnncc")

cacique <- read.csv("C:/Users/User/Downloads/BD_AranasPeq_Cacique.csv")

blanca_p <- read_sheet("https://docs.google.com/spreadsheets/d/1qbhqdseQV4tVa_q_Eeega_SGncMr_jkIOLxvXzSlbKo/edit?gid=0#gid=0",
                       sheet = "Hoja 1",
                       col_types = "ccccc__nnDnnnnnncc")



```

```{r, echo=FALSE, eval=FALSE}
guiri2 <- guiri |> 
  mutate(area.cm2 = as.double(as.character(area.cm2)),
         num.frag = as.double(as.character(num.frag)),
         blanq = as.double(as.character(blanq)),
         mort. = as.double(as.character(mort.)),
         mort.parc = as.double(as.character(mort.parc)),
         perd= as.double(as.character(perd)))
```

# Some cleaning

```{r}
df <- rbind(guiri, pelonas, blanca)
df <- df |> 
  mutate(fecha = ym(paste(year, month, sep = "-")))
```

# Grafico con promedio-promedio

```{r, echo=FALSE}
paleta <- c("Playa Blanca" = "#192639", 
            "Playa Pelonas" = "#4EBCB8", 
            "Guiri" = "#FA9938", 
              "Cacique" = "#9E1B32")
```


```{r}
df |> 
  drop_na(area.cm2) |> 
  group_by(site, fecha) |>
  summarise(area_cm2 = mean(area.cm2)) |>
  ggplot()+
  geom_line(aes(x=fecha, y=area_cm2, colour = site))+
  geom_point(aes(x=fecha, y=area_cm2, colour = site))
```

# Gráfico con suma-promedio

## Arreglar la etiqueta de las aranas

```{r}
source("./Scripts/fix_structure_code.R")
df$str_fixed <- fix_structure(df$str.code)

# remover ciertos digitadores con datos repetidos
df <- df |> filter(!digitador %in% c("Patricia", "Andrea C.", 
                                     "Carmen", "Shantall"))
```

```{r}
df_resumen <- df |>
  drop_na(area.cm2) |>
  #filter(fecha < ymd("2026-09-01")) |> 
  filter(!(fecha == ymd("2024-10-01") & site == "Guiri")) |> 

  # 1️⃣ Sumar lados → total por estructura y mes
  group_by(site, str.code, fecha) |>
  summarise(
    total_area = sum(area.cm2),
    .groups = "drop"
  ) |>

  # 2️⃣ Promediar estructuras → promedio por sitio y mes
  group_by(site, fecha) |>
  summarise(
    mean_area = mean(total_area),
    .groups = "drop"
  )

# 3️⃣ Graficar
df_resumen |> 
  ggplot(aes(x = fecha, y = mean_area, colour = site, group = site)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  theme_classic() +
  theme(legend.position = "top", legend.title = element_blank()) +
  scale_color_manual(values = paleta,
                     labels = c("Güiri-Güiri", 
                                "Playa Blanca", 
                                "Playa Pelonas")) +
  scale_x_date(date_labels = "%b-%Y", date_breaks = "6 month") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    x = "",
    y = "Área promedio por estructura (cm²)",
  )

```

```{r}
png(filename = "./Results/grandes.png", res = 300, 
    width = 2400, 
    height = 1800)

dev.off()
```


# Estructuras pequeñas

```{r}
columnas <- c("str.code", "site", "month", "year", "area.cm2")

cacique_s <- cacique |> 
  select(columnas)

blanca_p_s <- blanca_p |> 
  select(columnas)

df_p <- rbind(cacique_s, blanca_p_s)
df_p <- df_p |> 
  mutate(area.cm2=as.numeric(area.cm2),
         fecha = ym(paste(year, month, sep = "-")))
```

## plot

```{r}
df_p |> 
  drop_na(area.cm2) |> 
  filter(site=="Playa Blanca") |> 
  group_by(site, fecha) |>
  summarise(area_cm2 = mean(area.cm2)) |>
  ggplot()+
  geom_line(aes(x=fecha, y=area_cm2, colour = site), linewidth = 1)+
  geom_point(aes(x=fecha, y=area_cm2, colour = site), size = 2)+
  theme_classic() +
  theme()+
  lims(y=c(min(df_p$area.cm2),2000))+
  labs(
    x = "",
    y = "Área promedio por estructura (cm2)",
  ) +
  theme(legend.position = "none", legend.title = element_blank()) +
  scale_x_date(date_labels = "%b-%Y", date_breaks = "6 month") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values = paleta,
                     labels = c("Cacique", "Playa Blanca"))
```


```{r}
png(filename = "./Results/pequenas.png", res = 300, 
    width = 2400, 
    height = 1400)

dev.off()
```




```{r}
blanca_p1 <- read.csv("C:/Users/User/Downloads/BD_AranasPeq_Blanca_con error.csv")

blanca_p2 <- read.csv("C:/Users/User/Downloads/BD_AranasPeq_Blanca.csv")
```

```{r}
conteos <- blanca_p1 |> group_by(photo.code) |> mutate(numero = n())
reps <- conteos |> filter(numero>1)



max(conteos$numero)
which(conteos$numero==46)
```










