---
title: "models"
author: "R. Hidalgo"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

Libraries

```{r}
library(tidyverse)
library(lme4)
library(glmmTMB)
library(mgcv)
library(DHARMa)
library(sjPlot)
library(MASS)
```

# Big structures

## First model with Playa Blanca and Güiri

Build model and check residuals

```{r}
m5 <- glmmTMB(area.cm2 ~ poly(date, 2) * site + (1|structure_fixed),
                 data = df_1,
                 ziformula = ~ 1,
                 family = tweedie())

summary(m5)
DHARMa::simulateResiduals(fittedModel = m5, plot = TRUE)
```

Visualize model predictions

```{r}
# If that fails, generate predictions manually:
new_data <- expand.grid(site=levels(df_1$site),
                        date = seq(as.Date("2021-01-01"),
                                        as.Date("2024-05-01"),
                                        by = "month"),
                        structure_fixed=levels(df_1$structure_fixed))

# Include poly() terms manually
new_data$poly1 <- poly(df_1$date, 2)[,1][1:1148]
new_data$poly2 <- poly(df_1$date, 2)[,2][1:1148]

# Rename for consistency with model
names(new_data)[which(names(new_data) == "poly1")] <- "poly(date, 2)1"
names(new_data)[which(names(new_data) == "poly2")] <- "poly(date, 2)2"

new_data$preds <- predict(m5, newdata = new_data, type = "response")

# Plot with ggplot2
ggplot(new_data, aes(x = date, y = preds, col=site)) +
  stat_summary(geom = "line", fun = "mean", linewidth = 1) +
  labs(y = "Predicted area (cm²)", x = "Date")+
  scale_color_manual(values = paleta[c(2,3)],
                     labels = c("Güiri", "Playa Blanca"))+
  theme_classic()+
  theme(legend.position = "top",
        legend.title = element_blank()) 
```

check random  effects

```{r}
plot_model(m5, type = "est", transform = NULL)

# random effecrs, structure
ranef(m5)
plot_model(m5, type = "re", transform = NULL)
```

comparisons

```{r}
library(emmeans)

# Get estimated marginal means and compare sites (start-medium-end)
time_points <- data.frame(
    date = as.Date(c("2021-01-01", "2022-06-01", "2024-05-01"))
)

emm <- emmeans(m5, 
               specs = ~ site | date,
               at = list(date = time_points$date))

pairs(emm)  # This gives you the contrast between sites

# For more detailed output including confidence intervals
contrast_results <- pairs(emm, infer = TRUE)
print(contrast_results)
```

plot emmeans

```{r}
df_1 |> 
  filter(date == "2021-01-01" | date == "2022-06-01" | date == "2024-05-01") |> 
  ggplot(aes(x=site, y=area.cm2, col=site)) +
  facet_wrap(~date, scales = "free_x") +
  geom_violin(alpha = 0.5)+
  geom_jitter()+
  theme_bw()
```


## Second model with all 3 sites


```{r}
m8 <- glmmTMB(area.cm2 ~ poly(date, 3) * site + (1|structure_fixed),
                 data = df_2,
                 ziformula = ~ 1,
                 family = tweedie())


DHARMa::simulateResiduals(fittedModel = m8, plot = TRUE)
summary(m8)
```

```{r}
# If that fails, generate predictions manually:
new_data <- expand.grid(site=levels(df_2$site),
                        date = seq(as.Date("2022-01-01"),
                                        as.Date("2023-02-01"),
                                        by = "month"),
                        structure_fixed=levels(df_2$structure_fixed))

# Include poly() terms manually
new_data$poly1 <- poly(df_2$date, 2)[,1][1:1806]
new_data$poly2 <- poly(df_2$date, 2)[,2][1:1806]

# Rename for consistency with model
names(new_data)[which(names(new_data) == "poly1")] <- "poly(date, 2)1"
names(new_data)[which(names(new_data) == "poly2")] <- "poly(date, 2)2"

new_data$preds <- predict(m8, newdata = new_data, type = "response")

# Plot with ggplot2
ggplot(new_data, aes(x = date, y = preds, col=site)) +
  stat_summary(geom = "line", fun = "mean", linewidth = 1) +
  labs(y = "Predicted area (cm²)", x = "Date")+
  scale_color_manual(values = paleta[],)+
  theme_classic()+
  theme(legend.position = "top",
        legend.title = element_blank()) 
```

```{r}
plot_model(m8, type = "est", transform = NULL)

# random effecrs, structure
ranef(m8)
plot_model(m8, type = "re", transform = NULL)
```

# Small structures

